version: "2"
services:
  gitlab: #port 9xxx
    build: gitlab/.
    ports: #ERROR: Invalid port specification: "533302"
      - 9080:80
      - 9443:443
      # - 9022:22 #ERROR: Invalid port specification: "533302"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab

  jenkins: #port 8xxx
    build: jenkins/.
    ports:
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home

  clair:
    build: clair/.
    volumes:
     - clair-data:/var/local
     - ./clair/config:/config
    ports:
      - 6060:6060
      - 6061:6061
    command: ["--config=/config/clair.yml"]

  auth:
    build: registry/auth/.
    ports:
      - 5001:5001
    volumes:
      - ./registry/auth//config:/config:ro
      - ./registry/auth//ssl:/ssl
    command: /config/auth_config.yml

  registry:
    build: registry/.
    ports:
      - 5000:5000
    volumes:
      - ./registry/auth/ssl:/ssl
      - registry-data:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=https://auth:5001/auth
      - REGISTRY_AUTH_TOKEN_SERVICE="registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="auth_service"
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem

  hyperclair:
    build: hyperclair/.
    volumes:
      - hyperclair-data:/data
    ports:
      - 9999:9999

volumes:
  gitlab-data:
    driver: local
  gitlab-config:
     driver: local
  jenkins-data:
    driver: local
  clair-data:
    driver: local
  registry-data:
    driver: local
  hyperclair-data:
    driver: local
